name: Build Executables

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install pymupdf pandas openpyxl pyinstaller
      - run: pyinstaller --onefile read_pdf_highlights_FINAL.py
      - uses: actions/upload-artifact@v2
        with:
          name: mac-executable
          path: dist/read_pdf_highlights_FINAL
